server:
  port: 8080

spring:
  application:
    name: eks-gitops-deploy

management:
  endpoints:
    web:
      exposure:
        include: health,info,metrics
  endpoint:
    health:
      show-details: always
      probes:
        enabled: true
  health:
    livenessstate:
      enabled: true
    readinessstate:
      enabled: true

# App metadata
app:
  version: "1.0.0"
  blueprint: "Kestra EKS Pipeline"
  author: "Abhishek Khode"
